FROM node:22-alpine

WORKDIR /app

COPY package.json /app/package.json
RUN npm install

COPY . /app

RUN npm run build

ENV NODE_ENV=production
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

CMD ["npm", "start"]
