import { NextResponse } from "next/server";

const ENGINE_URL = (process.env.FPL_ENGINE_URL || "https://pitchiq-python-production.up.railway.app").replace(/\/$/, "");

function jsonError(message: string, status = 502) {
  return NextResponse.json({ error: message }, { status });
}

async function engineFetch(path: string, init?: RequestInit) {
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), 20_000);
  try {
    const response = await fetch(ENGINE_URL + path, {
      ...init,
      cache: "no-store",
      signal: controller.signal,
      headers: {
        accept: "application/json",
        ...(init?.headers || {}),
      },
    });
    const text = await response.text();
    let payload: any;
    try {
      payload = text ? JSON.parse(text) : {};
    } catch {
      throw new Error("FPL engine returned invalid JSON.");
    }
    if (!response.ok) {
      throw new Error(payload?.error || `FPL engine request failed (${response.status}).`);
    }
    return payload;
  } finally {
    clearTimeout(timeout);
  }
}

function positionName(value: unknown) {
  const map: Record<number, string> = { 1: "GK", 2: "DEF", 3: "MID", 4: "FWD" };
  return map[Number(value)] || String(value || "");
}

function mapEngineDashboard(teamId: number, dashboard: any, profile: any) {
  const manager = dashboard.manager || {};
  const ranking = dashboard.current_squad?.ranking || [];
  const squad: Array<Record<string, any>> = Array.isArray(profile?.squad) ? profile.squad : [];

  const byId = new Map<number, Record<string, any>>(
    squad.map((player: Record<string, any>) => [Number(player.id), player])
  );
  const players = ranking.map((row: Record<string, any>) => {
    const source = byId.get(Number(row.id)) || {};
    return {
      id: Number(row.id),
      name: row.name || source.web_name || "Unknown",
      position: row.position || positionName(source.position_id),
      price: Number(source.current_price || source.price || 0),
      team: row.team || source.team || "Unknown",
      status: source.status || "a",
      expectedPoints: Number(row.expected_points || 0),
      confidence: Number(row.confidence || 0),
      starter: Boolean(row.starter),
    };
  });

  const suggestions: Array<Record<string, any>> = Array.isArray(dashboard.transfers?.suggestions)
    ? dashboard.transfers.suggestions
    : [];
  const opportunities = suggestions
    .filter((item: any) => item?.action === "transfer")
    .map((item: any) => ({
      sell: item.sell?.name || "",
      buy: item.buy?.name || "",
      position: item.position || "",
      netExpectedGain: Number(item.net_expected_gain || 0),
      gain1: Number(item.gain_1 || 0),
      gain3: Number(item.gain_3 || 0),
      gain6: Number(item.gain_6 || 0),
      confidence: Number(item.confidence || 0),
      hitCost: Number(item.hit_cost || 0),
      bankAfter: Number(item.bank_after || 0),
      reason: item.why || "Projected improvement.",
      risk: Array.isArray(item.risks) ? item.risks.join("; ") : "Model uncertainty",
      horizon: String(dashboard.filters?.horizon || 6) + " GW",
      expectedMinutesDifference: item.expected_minutes_delta ?? null,
      fixtureImpact: item.fixture_swing ?? null,
      budgetAssumption: item.budget_assumption || null,
      dataTimestamp: dashboard.generated_at,
    }));

  const decision = dashboard.decision || {};
  const baseline = {
    action: decision.action === "hold" ? "DO NOTHING" : "DO NOTHING",
    reason: decision.summary || "No transfer clears the action threshold.",
  };

  return {
    teamId,
    event: Number(dashboard.planning_event || manager.imported_gameweek || 0),
    deadline: null,
    retrievedAt: dashboard.generated_at || new Date().toISOString(),
    bank: Number(manager.bank || 0),
    freeTransfers: Number(manager.free_transfers || 0),
    players,
    opportunities: opportunities.slice(0, 5),
    baseline,
    model: {
      version: "fpl-engine",
      method: "Recovered FPL PitchIQ projection, minutes, fixture, transfer and risk engine",
      calibration: dashboard.reliability?.status || "collecting",
      note: dashboard.freshness?.used_stale_data
        ? "Official source refresh was unavailable; the engine marked its installed data as stale."
        : "Recommendations are generated by the deployed Python engine.",
    },
    engine: {
      status: dashboard.status,
      decision,
      transfers: dashboard.transfers,
      squadRating: dashboard.squad_rating,
      currentSquad: dashboard.current_squad,
      optimizedSquad: dashboard.optimized_squad,
      reliability: dashboard.reliability,
      freshness: dashboard.freshness,
      sources: dashboard.sources,
    },
  };
}

export async function GET(_: Request, ctx: { params: Promise<{ id: string }> }) {
  const { id } = await ctx.params;
  const teamId = Number(id);

  if (!Number.isInteger(teamId) || teamId <= 0) {
    return jsonError("Invalid public FPL Team ID.", 400);
  }

  try {
    await engineFetch("/api/health");

    await engineFetch("/api/import-team", {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({ team_id: teamId }),
    });

    const [dashboard, profile] = await Promise.all([
      engineFetch("/api/dashboard"),
      engineFetch("/api/profile"),
    ]);

    return NextResponse.json(mapEngineDashboard(teamId, dashboard, profile));
  } catch (error) {
    const message =
      error instanceof Error && error.name === "AbortError"
        ? "FPL engine request timed out."
        : error instanceof Error
          ? error.message
          : "Unable to load the FPL engine.";

    return jsonError(message);
  }
}
