"use client";
import {useState} from "react";
type SquadPlayer={id:number;name:string;position:string;price:number;team:string;status:string};
export default function Home(){
 const [teamId,setTeamId]=useState(""); const [players,setPlayers]=useState<SquadPlayer[]>([]); const [event,setEvent]=useState<number|null>(null); const [updated,setUpdated]=useState<string|null>(null); const [loading,setLoading]=useState(false); const [error,setError]=useState("");
 async function analyze(){setError("");const id=Number(teamId);if(!Number.isInteger(id)||id<=0){setError("Enter a valid public FPL Team ID.");return}setLoading(true);try{const r=await fetch("/api/team/"+id,{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to load that team.");setPlayers(d.players);setEvent(d.event);setUpdated(d.retrievedAt)}catch(e){setError(e instanceof Error?e.message:"Unable to load team.")}finally{setLoading(false)}}
 return <main><header className="topbar"><div className="brand"><span className="mark">IQ</span>FPL PitchIQ</div><span className="status">LIVE FPL DATA</span></header>
 <section className="hero"><div className="eyebrow">DECISION ENGINE · EXPLAINABLE FPL</div><h1>Your best FPL move,<br/><em>explained.</em></h1><p>Import your squad and compare transfers with rolling — using projected gain, expected minutes, fixtures, risk and future flexibility.</p><div className="import"><label htmlFor="team">Public FPL Team ID</label><div className="inputrow"><input id="team" inputMode="numeric" value={teamId} onChange={e=>setTeamId(e.target.value)} placeholder="e.g. 1234567"/><button onClick={analyze} disabled={loading}>{loading?"Analyzing…":"Analyze my team"}</button></div><small>No FPL password required.</small></div>{error&&<div className="error">{error}</div>}</section>
 <section className="trust"><div><b>{event?"GW "+event:"Dynamic GW"}</b><span>authoritative event state</span></div><div><b>{updated?"Synced":"Awaiting squad"}</b><span>{updated?"fresh FPL retrieval":"data freshness"}</span></div><div><b>Model v0.1</b><span>projection layer</span></div><div><b>Evidence first</b><span>no fabricated accuracy claims</span></div></section>
 {players.length>0&&<section className="dashboard"><div className="sectionhead"><div><div className="eyebrow">YOUR SQUAD</div><h2>Decision starting point</h2></div><span className="pill">Squad synced</span></div><div className="grid"><div className="card roster"><h3>Imported players</h3>{players.map(p=><div className="player" key={p.id}><span><b>{p.name}</b><small>{p.position} · {p.team} · {p.status}</small></span><span>£{p.price.toFixed(1)}m</span></div>)}</div><div className="card decision"><div className="cardlabel">BASELINE</div><h3>Roll / Do Nothing</h3><div className="big">KEEP THE SQUAD</div><p>Every transfer will be compared with rolling. Acting only makes sense when the risk-adjusted improvement clears the cost of the move and preserves enough future flexibility.</p><div className="metrics"><span><b>—</b><small>Net gain</small></span><span><b>—</b><small>Confidence</small></span><span><b>—</b><small>Hit cost</small></span></div></div></div></section>}
 <section className="how"><div><div className="eyebrow">HOW IT WORKS</div><h2>Import → Compare → Decide</h2></div><div className="steps"><article><b>01</b><h3>Import</h3><p>Use your public Team ID. No password and no credentials stored.</p></article><article><b>02</b><h3>Compare</h3><p>Evaluate transfer paths against rolling, with assumptions visible.</p></article><article><b>03</b><h3>Decide</h3><p>See gain, risk, minutes, fixtures, alternatives and planning horizon.</p></article></div></section>
 <section className="trustbox"><div className="eyebrow">MODEL PERFORMANCE</div><h2>Evidence before accuracy claims.</h2><p>PitchIQ will publish measured historical performance with sample sizes, baselines and calibration — not a marketing score without methodology.</p><a href="/model-performance">Read the methodology →</a></section>
 <footer><span>FPL PitchIQ</span><span>Public Team ID only · No FPL password required</span></footer></main>
}